package rest.mybatis.dao.meettingroom;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import rest.mybatis.model.meettingroom.MrMeettingEmployee;
import rest.mybatis.model.meettingroom.MrSpOrder;
import rest.mybatis.model.meettingroom.MrUserT;

public interface MrMeettingEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByUserIdAndMid(@Param("userId")Integer userId,@Param("mId")Integer mId);
    int deleteByMeettingId(Integer mId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insert(MrMeettingEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insertSelective(MrMeettingEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    MrMeettingEmployee selectByPrimaryKey(Integer id);
    //MrMeettingEmployee selectByemployeeId(Integer userId);
    List<MrMeettingEmployee> selectBymeettingId(Integer meettingId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKeySelective(MrMeettingEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEETTING_EMPLOYEE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKey(MrMeettingEmployee record);
}