package rest.mybatis.dao.meettingroom;

import java.util.List;

import rest.mybatis.model.meettingroom.MrSpDownload;

public interface MrSpDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insert(MrSpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insertSelective(MrSpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    MrSpDownload selectByPrimaryKey(Integer id);
    List<MrSpDownload> selectAlldownload();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKeySelective(MrSpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SP_DOWNLOAD
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKey(MrSpDownload record);
}