package rest.mybatis.dao.meettingroom;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import rest.mybatis.model.meettingroom.MrDepartmentWithBLOBs;
import rest.mybatis.model.meettingroom.MrUserT;

public interface MrUserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insert(MrUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int insertSelective(MrUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    MrUserT selectByPrimaryKey(@Param(value="userId")Integer userId);
    List<MrUserT> selectByName(String userName);
    MrDepartmentWithBLOBs selectDepartmentByID(Integer departmentId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKeySelective(MrUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MrUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    int updateByPrimaryKey(MrUserT record);
}