package rest.mybatis.model.meettingroom;

public class MrDepartmentWithBLOBs extends MrDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Description
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String departmentDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Address
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String departmentAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Description
     *
     * @return the value of Department.Department_Description
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getDepartmentDescription() {
        return departmentDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Description
     *
     * @param departmentDescription the value for Department.Department_Description
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentDescription(String departmentDescription) {
        this.departmentDescription = departmentDescription == null ? null : departmentDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Address
     *
     * @return the value of Department.Department_Address
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getDepartmentAddress() {
        return departmentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Address
     *
     * @param departmentAddress the value for Department.Department_Address
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentAddress(String departmentAddress) {
        this.departmentAddress = departmentAddress == null ? null : departmentAddress.trim();
    }
}