package rest.mybatis.model.meettingroom;

public class MrDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Name
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Code
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.City_Id
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Level
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer departmentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Validity
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer departmentValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Type
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer departmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Department_Mark
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer departmentMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.K3_DEPT_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer k3DeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.SPECIAL_MARKS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer specialMarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.SPECIAL_PROJECT_K3
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer specialProjectK3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.COST_OF_BEAR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer costOfBear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.SALE_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer saleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.DISPLAY_INDEX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer displayIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.FLOOR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.FAX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.CORPRATION_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer corprationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.PRODUCT_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer productFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_ID
     *
     * @return the value of Department.Department_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_ID
     *
     * @param departmentId the value for Department.Department_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Name
     *
     * @return the value of Department.Department_Name
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Name
     *
     * @param departmentName the value for Department.Department_Name
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Code
     *
     * @return the value of Department.Department_Code
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Code
     *
     * @param departmentCode the value for Department.Department_Code
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.City_Id
     *
     * @return the value of Department.City_Id
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.City_Id
     *
     * @param cityId the value for Department.City_Id
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Level
     *
     * @return the value of Department.Department_Level
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDepartmentLevel() {
        return departmentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Level
     *
     * @param departmentLevel the value for Department.Department_Level
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentLevel(Integer departmentLevel) {
        this.departmentLevel = departmentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Validity
     *
     * @return the value of Department.Department_Validity
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDepartmentValidity() {
        return departmentValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Validity
     *
     * @param departmentValidity the value for Department.Department_Validity
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentValidity(Integer departmentValidity) {
        this.departmentValidity = departmentValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Type
     *
     * @return the value of Department.Department_Type
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDepartmentType() {
        return departmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Type
     *
     * @param departmentType the value for Department.Department_Type
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentType(Integer departmentType) {
        this.departmentType = departmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.Department_Mark
     *
     * @return the value of Department.Department_Mark
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDepartmentMark() {
        return departmentMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.Department_Mark
     *
     * @param departmentMark the value for Department.Department_Mark
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartmentMark(Integer departmentMark) {
        this.departmentMark = departmentMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.K3_DEPT_ID
     *
     * @return the value of Department.K3_DEPT_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getK3DeptId() {
        return k3DeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.K3_DEPT_ID
     *
     * @param k3DeptId the value for Department.K3_DEPT_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setK3DeptId(Integer k3DeptId) {
        this.k3DeptId = k3DeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.SPECIAL_MARKS
     *
     * @return the value of Department.SPECIAL_MARKS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getSpecialMarks() {
        return specialMarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.SPECIAL_MARKS
     *
     * @param specialMarks the value for Department.SPECIAL_MARKS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setSpecialMarks(Integer specialMarks) {
        this.specialMarks = specialMarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.SPECIAL_PROJECT_K3
     *
     * @return the value of Department.SPECIAL_PROJECT_K3
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getSpecialProjectK3() {
        return specialProjectK3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.SPECIAL_PROJECT_K3
     *
     * @param specialProjectK3 the value for Department.SPECIAL_PROJECT_K3
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setSpecialProjectK3(Integer specialProjectK3) {
        this.specialProjectK3 = specialProjectK3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.COST_OF_BEAR
     *
     * @return the value of Department.COST_OF_BEAR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getCostOfBear() {
        return costOfBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.COST_OF_BEAR
     *
     * @param costOfBear the value for Department.COST_OF_BEAR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setCostOfBear(Integer costOfBear) {
        this.costOfBear = costOfBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.SALE_FLAG
     *
     * @return the value of Department.SALE_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getSaleFlag() {
        return saleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.SALE_FLAG
     *
     * @param saleFlag the value for Department.SALE_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setSaleFlag(Integer saleFlag) {
        this.saleFlag = saleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.DISPLAY_INDEX
     *
     * @return the value of Department.DISPLAY_INDEX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.DISPLAY_INDEX
     *
     * @param displayIndex the value for Department.DISPLAY_INDEX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDisplayIndex(Integer displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.FLOOR
     *
     * @return the value of Department.FLOOR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.FLOOR
     *
     * @param floor the value for Department.FLOOR
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.FAX
     *
     * @return the value of Department.FAX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.FAX
     *
     * @param fax the value for Department.FAX
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.CORPRATION_ID
     *
     * @return the value of Department.CORPRATION_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getCorprationId() {
        return corprationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.CORPRATION_ID
     *
     * @param corprationId the value for Department.CORPRATION_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setCorprationId(Integer corprationId) {
        this.corprationId = corprationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.PRODUCT_FLAG
     *
     * @return the value of Department.PRODUCT_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getProductFlag() {
        return productFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.PRODUCT_FLAG
     *
     * @param productFlag the value for Department.PRODUCT_FLAG
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setProductFlag(Integer productFlag) {
        this.productFlag = productFlag;
    }
}