package rest.mybatis.model.meettingroom;

import java.util.List;

public class MrSpOrder {
	private MrMeettingRoom mrMeettingRoom;
	
	private List<MrUserT> mrUserTList;
    public List<MrUserT> getMrUserTList() {
		return mrUserTList;
	}

	public void setMrUserTList(List<MrUserT> mrUserTList) {
		this.mrUserTList = mrUserTList;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.DEPARTMENT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.ORGANIZATION
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.MEETTING_NAME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String meettingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.PEOPLE_NUMBERS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer peopleNumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.END_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.START_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.END_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.MEETTING_ROOM_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private Integer meettingRoomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SP_ORDER.MEETTING_TITLE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    private String meettingTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.ID
     *
     * @return the value of SP_ORDER.ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.ID
     *
     * @param id the value for SP_ORDER.ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.DEPARTMENT
     *
     * @return the value of SP_ORDER.DEPARTMENT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.DEPARTMENT
     *
     * @param department the value for SP_ORDER.DEPARTMENT
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.ORGANIZATION
     *
     * @return the value of SP_ORDER.ORGANIZATION
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.ORGANIZATION
     *
     * @param organization the value for SP_ORDER.ORGANIZATION
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.MEETTING_NAME
     *
     * @return the value of SP_ORDER.MEETTING_NAME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getMeettingName() {
        return meettingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.MEETTING_NAME
     *
     * @param meettingName the value for SP_ORDER.MEETTING_NAME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setMeettingName(String meettingName) {
        this.meettingName = meettingName == null ? null : meettingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.PEOPLE_NUMBERS
     *
     * @return the value of SP_ORDER.PEOPLE_NUMBERS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getPeopleNumbers() {
        return peopleNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.PEOPLE_NUMBERS
     *
     * @param peopleNumbers the value for SP_ORDER.PEOPLE_NUMBERS
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setPeopleNumbers(Integer peopleNumbers) {
        this.peopleNumbers = peopleNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.START_TIME
     *
     * @return the value of SP_ORDER.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.START_TIME
     *
     * @param startTime the value for SP_ORDER.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.END_TIME
     *
     * @return the value of SP_ORDER.END_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.END_TIME
     *
     * @param endTime the value for SP_ORDER.END_TIME
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.START_DATE
     *
     * @return the value of SP_ORDER.START_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.START_DATE
     *
     * @param startDate the value for SP_ORDER.START_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.END_DATE
     *
     * @return the value of SP_ORDER.END_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.END_DATE
     *
     * @param endDate the value for SP_ORDER.END_DATE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.MEETTING_ROOM_ID
     *
     * @return the value of SP_ORDER.MEETTING_ROOM_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public Integer getMeettingRoomId() {
        return meettingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.MEETTING_ROOM_ID
     *
     * @param meettingRoomId the value for SP_ORDER.MEETTING_ROOM_ID
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setMeettingRoomId(Integer meettingRoomId) {
        this.meettingRoomId = meettingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SP_ORDER.MEETTING_TITLE
     *
     * @return the value of SP_ORDER.MEETTING_TITLE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public String getMeettingTitle() {
        return meettingTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SP_ORDER.MEETTING_TITLE
     *
     * @param meettingTitle the value for SP_ORDER.MEETTING_TITLE
     *
     * @mbggenerated Tue Dec 06 16:40:32 CST 2016
     */
    public void setMeettingTitle(String meettingTitle) {
        this.meettingTitle = meettingTitle == null ? null : meettingTitle.trim();
    }

	public MrMeettingRoom getMrMeettingRoom() {
		return mrMeettingRoom;
	}

	public void setMrMeettingRoom(MrMeettingRoom mrMeettingRoom) {
		this.mrMeettingRoom = mrMeettingRoom;
	}
    
}