package rest.mybatis.model.test;

public class PlineWithBLOBs extends Pline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PLIN_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String plinNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PLIN_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String plinNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String proStruct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.WORK_FLOW
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String workFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String keyProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.TYPE_APP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String typeApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PLIN_COMMENT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String plinComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PLIN_NAME_CN
     *
     * @return the value of T_PLIN.PLIN_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPlinNameCn() {
        return plinNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PLIN_NAME_CN
     *
     * @param plinNameCn the value for T_PLIN.PLIN_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPlinNameCn(String plinNameCn) {
        this.plinNameCn = plinNameCn == null ? null : plinNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.DES
     *
     * @return the value of T_PLIN.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.DES
     *
     * @param des the value for T_PLIN.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.REMARK
     *
     * @return the value of T_PLIN.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.REMARK
     *
     * @param remark the value for T_PLIN.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PLIN_NAME_EN
     *
     * @return the value of T_PLIN.PLIN_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPlinNameEn() {
        return plinNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PLIN_NAME_EN
     *
     * @param plinNameEn the value for T_PLIN.PLIN_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPlinNameEn(String plinNameEn) {
        this.plinNameEn = plinNameEn == null ? null : plinNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PRO_STRUCT
     *
     * @return the value of T_PLIN.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getProStruct() {
        return proStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PRO_STRUCT
     *
     * @param proStruct the value for T_PLIN.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setProStruct(String proStruct) {
        this.proStruct = proStruct == null ? null : proStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.WORK_FLOW
     *
     * @return the value of T_PLIN.WORK_FLOW
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getWorkFlow() {
        return workFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.WORK_FLOW
     *
     * @param workFlow the value for T_PLIN.WORK_FLOW
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setWorkFlow(String workFlow) {
        this.workFlow = workFlow == null ? null : workFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.KEY_PROP
     *
     * @return the value of T_PLIN.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getKeyProp() {
        return keyProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.KEY_PROP
     *
     * @param keyProp the value for T_PLIN.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setKeyProp(String keyProp) {
        this.keyProp = keyProp == null ? null : keyProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.TYPE_APP
     *
     * @return the value of T_PLIN.TYPE_APP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getTypeApp() {
        return typeApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.TYPE_APP
     *
     * @param typeApp the value for T_PLIN.TYPE_APP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setTypeApp(String typeApp) {
        this.typeApp = typeApp == null ? null : typeApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PLIN_COMMENT
     *
     * @return the value of T_PLIN.PLIN_COMMENT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPlinComment() {
        return plinComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PLIN_COMMENT
     *
     * @param plinComment the value for T_PLIN.PLIN_COMMENT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPlinComment(String plinComment) {
        this.plinComment = plinComment == null ? null : plinComment.trim();
    }
}