package rest.mybatis.model.test;

import java.util.Date;

public class Pline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date valideDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date invalideDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.SINGLE_SYS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Byte singleSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer desFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PRO_MANAGER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer structFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.FLOW_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer flowFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.APP_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer appFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PLIN_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer plinIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PRO_MANAGER2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proManager2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PRO_MANAGER3
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proManager3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PLIN.PRO_LABEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proLabel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.ID
     *
     * @return the value of T_PLIN.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.ID
     *
     * @param id the value for T_PLIN.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.VALIDE_DATE
     *
     * @return the value of T_PLIN.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getValideDate() {
        return valideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.VALIDE_DATE
     *
     * @param valideDate the value for T_PLIN.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setValideDate(Date valideDate) {
        this.valideDate = valideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.INVALIDE_DATE
     *
     * @return the value of T_PLIN.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getInvalideDate() {
        return invalideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.INVALIDE_DATE
     *
     * @param invalideDate the value for T_PLIN.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setInvalideDate(Date invalideDate) {
        this.invalideDate = invalideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.SINGLE_SYS
     *
     * @return the value of T_PLIN.SINGLE_SYS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Byte getSingleSys() {
        return singleSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.SINGLE_SYS
     *
     * @param singleSys the value for T_PLIN.SINGLE_SYS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSingleSys(Byte singleSys) {
        this.singleSys = singleSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.DES_FILE
     *
     * @return the value of T_PLIN.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getDesFile() {
        return desFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.DES_FILE
     *
     * @param desFile the value for T_PLIN.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setDesFile(Integer desFile) {
        this.desFile = desFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PRO_MANAGER
     *
     * @return the value of T_PLIN.PRO_MANAGER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProManager() {
        return proManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PRO_MANAGER
     *
     * @param proManager the value for T_PLIN.PRO_MANAGER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProManager(Integer proManager) {
        this.proManager = proManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.VERSION
     *
     * @return the value of T_PLIN.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.VERSION
     *
     * @param version the value for T_PLIN.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.STRUCT_FILE
     *
     * @return the value of T_PLIN.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getStructFile() {
        return structFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.STRUCT_FILE
     *
     * @param structFile the value for T_PLIN.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setStructFile(Integer structFile) {
        this.structFile = structFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.FLOW_FILE
     *
     * @return the value of T_PLIN.FLOW_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getFlowFile() {
        return flowFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.FLOW_FILE
     *
     * @param flowFile the value for T_PLIN.FLOW_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setFlowFile(Integer flowFile) {
        this.flowFile = flowFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.APP_FILE
     *
     * @return the value of T_PLIN.APP_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getAppFile() {
        return appFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.APP_FILE
     *
     * @param appFile the value for T_PLIN.APP_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setAppFile(Integer appFile) {
        this.appFile = appFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PLIN_INDEX
     *
     * @return the value of T_PLIN.PLIN_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getPlinIndex() {
        return plinIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PLIN_INDEX
     *
     * @param plinIndex the value for T_PLIN.PLIN_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPlinIndex(Integer plinIndex) {
        this.plinIndex = plinIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.DEPT_ID
     *
     * @return the value of T_PLIN.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.DEPT_ID
     *
     * @param deptId the value for T_PLIN.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PRO_MANAGER2
     *
     * @return the value of T_PLIN.PRO_MANAGER2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProManager2() {
        return proManager2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PRO_MANAGER2
     *
     * @param proManager2 the value for T_PLIN.PRO_MANAGER2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProManager2(Integer proManager2) {
        this.proManager2 = proManager2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PRO_MANAGER3
     *
     * @return the value of T_PLIN.PRO_MANAGER3
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProManager3() {
        return proManager3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PRO_MANAGER3
     *
     * @param proManager3 the value for T_PLIN.PRO_MANAGER3
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProManager3(Integer proManager3) {
        this.proManager3 = proManager3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PLIN.PRO_LABEL
     *
     * @return the value of T_PLIN.PRO_LABEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProLabel() {
        return proLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PLIN.PRO_LABEL
     *
     * @param proLabel the value for T_PLIN.PRO_LABEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProLabel(Integer proLabel) {
        this.proLabel = proLabel;
    }
}