package rest.mybatis.model.test;

import java.util.Date;

public class Pro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer corporationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.MANUFACTURE_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer manufactureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_CODE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_FACE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proFace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_PRODUCER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proProducer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L1_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer l1Kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L2_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer l2Kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SH_FLA
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Byte shFla;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L1_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String l1Type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L2_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String l2Type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L1_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String l1Ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.L2_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String l2Ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PUB_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date pubDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRE_SALE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date preSaleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.OUTPUT_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date outputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.STOP_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date stopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.ABOLISH_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date abolishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_PUB_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proPubLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_CHOICE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proChoiceLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.APP_STATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Byte appState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.NEW_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Byte newPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_PSER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proPser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.STRUCTURE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer structurePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PUB_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer pubFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SOFT_PERCENT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double softPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.USE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer useLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRODUCT_CYC_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer productCycType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.FOREIGN_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer foreignFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRIVATE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer privatePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SOFT_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer softFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.NEW_CYC
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer newCyc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_K3_NAME
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proK3Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_K3_CORE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proK3Core;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_K3_NUMBER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proK3Number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_K3_UNIT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proK3Unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_K3_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proK3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.OWNER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.LAST_MODIFY_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.QUOTE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double quote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.AGENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double agentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.COST
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.QUOTE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double quote2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.AGENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double agentPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SOFT_FLAG_2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer softFlag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_DES_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String proDesEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SETTLEMENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double settlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.SETTLEMENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Double settlementPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.RELEASE_STATUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer releaseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.MARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.ISNEEDMARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer isneedmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.ID
     *
     * @return the value of T_PRO.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.ID
     *
     * @param id the value for T_PRO.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.CORPORATION_ID
     *
     * @return the value of T_PRO.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getCorporationId() {
        return corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.CORPORATION_ID
     *
     * @param corporationId the value for T_PRO.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setCorporationId(Integer corporationId) {
        this.corporationId = corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.MANUFACTURE_ID
     *
     * @return the value of T_PRO.MANUFACTURE_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getManufactureId() {
        return manufactureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.MANUFACTURE_ID
     *
     * @param manufactureId the value for T_PRO.MANUFACTURE_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setManufactureId(Integer manufactureId) {
        this.manufactureId = manufactureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_NAME_CN
     *
     * @return the value of T_PRO.PRO_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProNameCn() {
        return proNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_NAME_CN
     *
     * @param proNameCn the value for T_PRO.PRO_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProNameCn(String proNameCn) {
        this.proNameCn = proNameCn == null ? null : proNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_CODE
     *
     * @return the value of T_PRO.PRO_CODE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProCode() {
        return proCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_CODE
     *
     * @param proCode the value for T_PRO.PRO_CODE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProCode(String proCode) {
        this.proCode = proCode == null ? null : proCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_FACE
     *
     * @return the value of T_PRO.PRO_FACE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProFace() {
        return proFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_FACE
     *
     * @param proFace the value for T_PRO.PRO_FACE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProFace(Integer proFace) {
        this.proFace = proFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_PRODUCER
     *
     * @return the value of T_PRO.PRO_PRODUCER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProProducer() {
        return proProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_PRODUCER
     *
     * @param proProducer the value for T_PRO.PRO_PRODUCER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProProducer(Integer proProducer) {
        this.proProducer = proProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L1_KIND
     *
     * @return the value of T_PRO.L1_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getL1Kind() {
        return l1Kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L1_KIND
     *
     * @param l1Kind the value for T_PRO.L1_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL1Kind(Integer l1Kind) {
        this.l1Kind = l1Kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L2_KIND
     *
     * @return the value of T_PRO.L2_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getL2Kind() {
        return l2Kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L2_KIND
     *
     * @param l2Kind the value for T_PRO.L2_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL2Kind(Integer l2Kind) {
        this.l2Kind = l2Kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SH_FLA
     *
     * @return the value of T_PRO.SH_FLA
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Byte getShFla() {
        return shFla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SH_FLA
     *
     * @param shFla the value for T_PRO.SH_FLA
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setShFla(Byte shFla) {
        this.shFla = shFla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L1_TYPE
     *
     * @return the value of T_PRO.L1_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getL1Type() {
        return l1Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L1_TYPE
     *
     * @param l1Type the value for T_PRO.L1_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL1Type(String l1Type) {
        this.l1Type = l1Type == null ? null : l1Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L2_TYPE
     *
     * @return the value of T_PRO.L2_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getL2Type() {
        return l2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L2_TYPE
     *
     * @param l2Type the value for T_PRO.L2_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL2Type(String l2Type) {
        this.l2Type = l2Type == null ? null : l2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L1_VER
     *
     * @return the value of T_PRO.L1_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getL1Ver() {
        return l1Ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L1_VER
     *
     * @param l1Ver the value for T_PRO.L1_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL1Ver(String l1Ver) {
        this.l1Ver = l1Ver == null ? null : l1Ver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.L2_VER
     *
     * @return the value of T_PRO.L2_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getL2Ver() {
        return l2Ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.L2_VER
     *
     * @param l2Ver the value for T_PRO.L2_VER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setL2Ver(String l2Ver) {
        this.l2Ver = l2Ver == null ? null : l2Ver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PUB_DATE
     *
     * @return the value of T_PRO.PUB_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PUB_DATE
     *
     * @param pubDate the value for T_PRO.PUB_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRE_SALE_DATE
     *
     * @return the value of T_PRO.PRE_SALE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getPreSaleDate() {
        return preSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRE_SALE_DATE
     *
     * @param preSaleDate the value for T_PRO.PRE_SALE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPreSaleDate(Date preSaleDate) {
        this.preSaleDate = preSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.OUTPUT_DATE
     *
     * @return the value of T_PRO.OUTPUT_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getOutputDate() {
        return outputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.OUTPUT_DATE
     *
     * @param outputDate the value for T_PRO.OUTPUT_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setOutputDate(Date outputDate) {
        this.outputDate = outputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.STOP_DATE
     *
     * @return the value of T_PRO.STOP_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getStopDate() {
        return stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.STOP_DATE
     *
     * @param stopDate the value for T_PRO.STOP_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.ABOLISH_DATE
     *
     * @return the value of T_PRO.ABOLISH_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getAbolishDate() {
        return abolishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.ABOLISH_DATE
     *
     * @param abolishDate the value for T_PRO.ABOLISH_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setAbolishDate(Date abolishDate) {
        this.abolishDate = abolishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_PUB_LEVEL
     *
     * @return the value of T_PRO.PRO_PUB_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProPubLevel() {
        return proPubLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_PUB_LEVEL
     *
     * @param proPubLevel the value for T_PRO.PRO_PUB_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProPubLevel(Integer proPubLevel) {
        this.proPubLevel = proPubLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_CHOICE_LEVEL
     *
     * @return the value of T_PRO.PRO_CHOICE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProChoiceLevel() {
        return proChoiceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_CHOICE_LEVEL
     *
     * @param proChoiceLevel the value for T_PRO.PRO_CHOICE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProChoiceLevel(Integer proChoiceLevel) {
        this.proChoiceLevel = proChoiceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.APP_STATE
     *
     * @return the value of T_PRO.APP_STATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Byte getAppState() {
        return appState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.APP_STATE
     *
     * @param appState the value for T_PRO.APP_STATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setAppState(Byte appState) {
        this.appState = appState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.NEW_PRO
     *
     * @return the value of T_PRO.NEW_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Byte getNewPro() {
        return newPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.NEW_PRO
     *
     * @param newPro the value for T_PRO.NEW_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setNewPro(Byte newPro) {
        this.newPro = newPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_PSER
     *
     * @return the value of T_PRO.PRO_PSER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProPser() {
        return proPser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_PSER
     *
     * @param proPser the value for T_PRO.PRO_PSER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProPser(Integer proPser) {
        this.proPser = proPser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_INDEX
     *
     * @return the value of T_PRO.PRO_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProIndex() {
        return proIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_INDEX
     *
     * @param proIndex the value for T_PRO.PRO_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProIndex(Integer proIndex) {
        this.proIndex = proIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.STRUCTURE_PRO
     *
     * @return the value of T_PRO.STRUCTURE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getStructurePro() {
        return structurePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.STRUCTURE_PRO
     *
     * @param structurePro the value for T_PRO.STRUCTURE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setStructurePro(Integer structurePro) {
        this.structurePro = structurePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PUB_FLAG
     *
     * @return the value of T_PRO.PUB_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getPubFlag() {
        return pubFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PUB_FLAG
     *
     * @param pubFlag the value for T_PRO.PUB_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPubFlag(Integer pubFlag) {
        this.pubFlag = pubFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SOFT_PERCENT
     *
     * @return the value of T_PRO.SOFT_PERCENT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getSoftPercent() {
        return softPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SOFT_PERCENT
     *
     * @param softPercent the value for T_PRO.SOFT_PERCENT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSoftPercent(Double softPercent) {
        this.softPercent = softPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.USE_LEVEL
     *
     * @return the value of T_PRO.USE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getUseLevel() {
        return useLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.USE_LEVEL
     *
     * @param useLevel the value for T_PRO.USE_LEVEL
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setUseLevel(Integer useLevel) {
        this.useLevel = useLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRODUCT_CYC_TYPE
     *
     * @return the value of T_PRO.PRODUCT_CYC_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProductCycType() {
        return productCycType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRODUCT_CYC_TYPE
     *
     * @param productCycType the value for T_PRO.PRODUCT_CYC_TYPE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProductCycType(Integer productCycType) {
        this.productCycType = productCycType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.FOREIGN_FLAG
     *
     * @return the value of T_PRO.FOREIGN_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getForeignFlag() {
        return foreignFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.FOREIGN_FLAG
     *
     * @param foreignFlag the value for T_PRO.FOREIGN_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setForeignFlag(Integer foreignFlag) {
        this.foreignFlag = foreignFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRIVATE_PRO
     *
     * @return the value of T_PRO.PRIVATE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getPrivatePro() {
        return privatePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRIVATE_PRO
     *
     * @param privatePro the value for T_PRO.PRIVATE_PRO
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPrivatePro(Integer privatePro) {
        this.privatePro = privatePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SOFT_FLAG
     *
     * @return the value of T_PRO.SOFT_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getSoftFlag() {
        return softFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SOFT_FLAG
     *
     * @param softFlag the value for T_PRO.SOFT_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSoftFlag(Integer softFlag) {
        this.softFlag = softFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.NEW_CYC
     *
     * @return the value of T_PRO.NEW_CYC
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getNewCyc() {
        return newCyc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.NEW_CYC
     *
     * @param newCyc the value for T_PRO.NEW_CYC
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setNewCyc(Integer newCyc) {
        this.newCyc = newCyc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_K3_NAME
     *
     * @return the value of T_PRO.PRO_K3_NAME
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProK3Name() {
        return proK3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_K3_NAME
     *
     * @param proK3Name the value for T_PRO.PRO_K3_NAME
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProK3Name(String proK3Name) {
        this.proK3Name = proK3Name == null ? null : proK3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_K3_CORE
     *
     * @return the value of T_PRO.PRO_K3_CORE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProK3Core() {
        return proK3Core;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_K3_CORE
     *
     * @param proK3Core the value for T_PRO.PRO_K3_CORE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProK3Core(String proK3Core) {
        this.proK3Core = proK3Core == null ? null : proK3Core.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_K3_NUMBER
     *
     * @return the value of T_PRO.PRO_K3_NUMBER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProK3Number() {
        return proK3Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_K3_NUMBER
     *
     * @param proK3Number the value for T_PRO.PRO_K3_NUMBER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProK3Number(String proK3Number) {
        this.proK3Number = proK3Number == null ? null : proK3Number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_K3_UNIT
     *
     * @return the value of T_PRO.PRO_K3_UNIT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProK3Unit() {
        return proK3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_K3_UNIT
     *
     * @param proK3Unit the value for T_PRO.PRO_K3_UNIT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProK3Unit(String proK3Unit) {
        this.proK3Unit = proK3Unit == null ? null : proK3Unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_K3_ID
     *
     * @return the value of T_PRO.PRO_K3_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProK3Id() {
        return proK3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_K3_ID
     *
     * @param proK3Id the value for T_PRO.PRO_K3_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProK3Id(Integer proK3Id) {
        this.proK3Id = proK3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.OWNER
     *
     * @return the value of T_PRO.OWNER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.OWNER
     *
     * @param owner the value for T_PRO.OWNER
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.LAST_MODIFY_DATE
     *
     * @return the value of T_PRO.LAST_MODIFY_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.LAST_MODIFY_DATE
     *
     * @param lastModifyDate the value for T_PRO.LAST_MODIFY_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.QUOTE
     *
     * @return the value of T_PRO.QUOTE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getQuote() {
        return quote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.QUOTE
     *
     * @param quote the value for T_PRO.QUOTE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setQuote(Double quote) {
        this.quote = quote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.AGENT_PRICE
     *
     * @return the value of T_PRO.AGENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getAgentPrice() {
        return agentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.AGENT_PRICE
     *
     * @param agentPrice the value for T_PRO.AGENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setAgentPrice(Double agentPrice) {
        this.agentPrice = agentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.COST
     *
     * @return the value of T_PRO.COST
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.COST
     *
     * @param cost the value for T_PRO.COST
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.QUOTE2
     *
     * @return the value of T_PRO.QUOTE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getQuote2() {
        return quote2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.QUOTE2
     *
     * @param quote2 the value for T_PRO.QUOTE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setQuote2(Double quote2) {
        this.quote2 = quote2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.AGENT_PRICE2
     *
     * @return the value of T_PRO.AGENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getAgentPrice2() {
        return agentPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.AGENT_PRICE2
     *
     * @param agentPrice2 the value for T_PRO.AGENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setAgentPrice2(Double agentPrice2) {
        this.agentPrice2 = agentPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SOFT_FLAG_2
     *
     * @return the value of T_PRO.SOFT_FLAG_2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getSoftFlag2() {
        return softFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SOFT_FLAG_2
     *
     * @param softFlag2 the value for T_PRO.SOFT_FLAG_2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSoftFlag2(Integer softFlag2) {
        this.softFlag2 = softFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_DES_EN
     *
     * @return the value of T_PRO.PRO_DES_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getProDesEn() {
        return proDesEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_DES_EN
     *
     * @param proDesEn the value for T_PRO.PRO_DES_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProDesEn(String proDesEn) {
        this.proDesEn = proDesEn == null ? null : proDesEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SETTLEMENT_PRICE
     *
     * @return the value of T_PRO.SETTLEMENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SETTLEMENT_PRICE
     *
     * @param settlementPrice the value for T_PRO.SETTLEMENT_PRICE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSettlementPrice(Double settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.SETTLEMENT_PRICE2
     *
     * @return the value of T_PRO.SETTLEMENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Double getSettlementPrice2() {
        return settlementPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.SETTLEMENT_PRICE2
     *
     * @param settlementPrice2 the value for T_PRO.SETTLEMENT_PRICE2
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setSettlementPrice2(Double settlementPrice2) {
        this.settlementPrice2 = settlementPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.RELEASE_STATUS
     *
     * @return the value of T_PRO.RELEASE_STATUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getReleaseStatus() {
        return releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.RELEASE_STATUS
     *
     * @param releaseStatus the value for T_PRO.RELEASE_STATUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setReleaseStatus(Integer releaseStatus) {
        this.releaseStatus = releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.MARK
     *
     * @return the value of T_PRO.MARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.MARK
     *
     * @param mark the value for T_PRO.MARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.ISNEEDMARK
     *
     * @return the value of T_PRO.ISNEEDMARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getIsneedmark() {
        return isneedmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.ISNEEDMARK
     *
     * @param isneedmark the value for T_PRO.ISNEEDMARK
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setIsneedmark(Integer isneedmark) {
        this.isneedmark = isneedmark;
    }
}