package rest.mybatis.model.test;

public class ProBu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer corporationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.BU_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String buNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.BU_NAME_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String buNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.PRO_PM
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer proPm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.VALIDE_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer valideFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO_BU.BU_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer buKind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.ID
     *
     * @return the value of T_PRO_BU.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.ID
     *
     * @param id the value for T_PRO_BU.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.CORPORATION_ID
     *
     * @return the value of T_PRO_BU.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getCorporationId() {
        return corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.CORPORATION_ID
     *
     * @param corporationId the value for T_PRO_BU.CORPORATION_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setCorporationId(Integer corporationId) {
        this.corporationId = corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.DEPT_ID
     *
     * @return the value of T_PRO_BU.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.DEPT_ID
     *
     * @param deptId the value for T_PRO_BU.DEPT_ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.BU_NAME_CN
     *
     * @return the value of T_PRO_BU.BU_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getBuNameCn() {
        return buNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.BU_NAME_CN
     *
     * @param buNameCn the value for T_PRO_BU.BU_NAME_CN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setBuNameCn(String buNameCn) {
        this.buNameCn = buNameCn == null ? null : buNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.BU_NAME_EN
     *
     * @return the value of T_PRO_BU.BU_NAME_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getBuNameEn() {
        return buNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.BU_NAME_EN
     *
     * @param buNameEn the value for T_PRO_BU.BU_NAME_EN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setBuNameEn(String buNameEn) {
        this.buNameEn = buNameEn == null ? null : buNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.PRO_PM
     *
     * @return the value of T_PRO_BU.PRO_PM
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getProPm() {
        return proPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.PRO_PM
     *
     * @param proPm the value for T_PRO_BU.PRO_PM
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setProPm(Integer proPm) {
        this.proPm = proPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.VALIDE_FLAG
     *
     * @return the value of T_PRO_BU.VALIDE_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getValideFlag() {
        return valideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.VALIDE_FLAG
     *
     * @param valideFlag the value for T_PRO_BU.VALIDE_FLAG
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setValideFlag(Integer valideFlag) {
        this.valideFlag = valideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO_BU.BU_KIND
     *
     * @return the value of T_PRO_BU.BU_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getBuKind() {
        return buKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO_BU.BU_KIND
     *
     * @param buKind the value for T_PRO_BU.BU_KIND
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setBuKind(Integer buKind) {
        this.buKind = buKind;
    }
}