package rest.mybatis.model.test;

public class ProWithBLOBs extends Pro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String proNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String proDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String keyProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRO.PRO_DES2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String proDes2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.REMARK
     *
     * @return the value of T_PRO.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.REMARK
     *
     * @param remark the value for T_PRO.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_NAME_EN
     *
     * @return the value of T_PRO.PRO_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getProNameEn() {
        return proNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_NAME_EN
     *
     * @param proNameEn the value for T_PRO.PRO_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setProNameEn(String proNameEn) {
        this.proNameEn = proNameEn == null ? null : proNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_DES
     *
     * @return the value of T_PRO.PRO_DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getProDes() {
        return proDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_DES
     *
     * @param proDes the value for T_PRO.PRO_DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setProDes(String proDes) {
        this.proDes = proDes == null ? null : proDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.KEY_PROP
     *
     * @return the value of T_PRO.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getKeyProp() {
        return keyProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.KEY_PROP
     *
     * @param keyProp the value for T_PRO.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setKeyProp(String keyProp) {
        this.keyProp = keyProp == null ? null : keyProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRO.PRO_DES2
     *
     * @return the value of T_PRO.PRO_DES2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getProDes2() {
        return proDes2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRO.PRO_DES2
     *
     * @param proDes2 the value for T_PRO.PRO_DES2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setProDes2(String proDes2) {
        this.proDes2 = proDes2 == null ? null : proDes2.trim();
    }
}