package rest.mybatis.model.test;

public class PserWithBLOBs extends Pser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.PSER_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String pserNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String proStruct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.PSER_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String pserNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String keyProp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.PSER_NAME_CN
     *
     * @return the value of T_PSER.PSER_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPserNameCn() {
        return pserNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.PSER_NAME_CN
     *
     * @param pserNameCn the value for T_PSER.PSER_NAME_CN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPserNameCn(String pserNameCn) {
        this.pserNameCn = pserNameCn == null ? null : pserNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.DES
     *
     * @return the value of T_PSER.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.DES
     *
     * @param des the value for T_PSER.DES
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.PRO_STRUCT
     *
     * @return the value of T_PSER.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getProStruct() {
        return proStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.PRO_STRUCT
     *
     * @param proStruct the value for T_PSER.PRO_STRUCT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setProStruct(String proStruct) {
        this.proStruct = proStruct == null ? null : proStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.REMARK
     *
     * @return the value of T_PSER.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.REMARK
     *
     * @param remark the value for T_PSER.REMARK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.PSER_NAME_EN
     *
     * @return the value of T_PSER.PSER_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPserNameEn() {
        return pserNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.PSER_NAME_EN
     *
     * @param pserNameEn the value for T_PSER.PSER_NAME_EN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPserNameEn(String pserNameEn) {
        this.pserNameEn = pserNameEn == null ? null : pserNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.KEY_PROP
     *
     * @return the value of T_PSER.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getKeyProp() {
        return keyProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.KEY_PROP
     *
     * @param keyProp the value for T_PSER.KEY_PROP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setKeyProp(String keyProp) {
        this.keyProp = keyProp == null ? null : keyProp.trim();
    }
}