package rest.mybatis.model.test;

import java.util.Date;

public class Pser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.PLIN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer plin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date valideDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Date invalideDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer desFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer structFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.CASES
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String cases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.CASES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer casesFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.PSER_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Integer pserIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PSER.MODULUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    private Float modulus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.ID
     *
     * @return the value of T_PSER.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.ID
     *
     * @param id the value for T_PSER.ID
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.PLIN
     *
     * @return the value of T_PSER.PLIN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getPlin() {
        return plin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.PLIN
     *
     * @param plin the value for T_PSER.PLIN
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPlin(Integer plin) {
        this.plin = plin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.VALIDE_DATE
     *
     * @return the value of T_PSER.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getValideDate() {
        return valideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.VALIDE_DATE
     *
     * @param valideDate the value for T_PSER.VALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setValideDate(Date valideDate) {
        this.valideDate = valideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.INVALIDE_DATE
     *
     * @return the value of T_PSER.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Date getInvalideDate() {
        return invalideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.INVALIDE_DATE
     *
     * @param invalideDate the value for T_PSER.INVALIDE_DATE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setInvalideDate(Date invalideDate) {
        this.invalideDate = invalideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.DES_FILE
     *
     * @return the value of T_PSER.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getDesFile() {
        return desFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.DES_FILE
     *
     * @param desFile the value for T_PSER.DES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setDesFile(Integer desFile) {
        this.desFile = desFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.STRUCT_FILE
     *
     * @return the value of T_PSER.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getStructFile() {
        return structFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.STRUCT_FILE
     *
     * @param structFile the value for T_PSER.STRUCT_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setStructFile(Integer structFile) {
        this.structFile = structFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.CASES
     *
     * @return the value of T_PSER.CASES
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getCases() {
        return cases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.CASES
     *
     * @param cases the value for T_PSER.CASES
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setCases(String cases) {
        this.cases = cases == null ? null : cases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.CASES_FILE
     *
     * @return the value of T_PSER.CASES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getCasesFile() {
        return casesFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.CASES_FILE
     *
     * @param casesFile the value for T_PSER.CASES_FILE
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setCasesFile(Integer casesFile) {
        this.casesFile = casesFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.VERSION
     *
     * @return the value of T_PSER.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.VERSION
     *
     * @param version the value for T_PSER.VERSION
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.PSER_INDEX
     *
     * @return the value of T_PSER.PSER_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Integer getPserIndex() {
        return pserIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.PSER_INDEX
     *
     * @param pserIndex the value for T_PSER.PSER_INDEX
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setPserIndex(Integer pserIndex) {
        this.pserIndex = pserIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PSER.MODULUS
     *
     * @return the value of T_PSER.MODULUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public Float getModulus() {
        return modulus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PSER.MODULUS
     *
     * @param modulus the value for T_PSER.MODULUS
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    public void setModulus(Float modulus) {
        this.modulus = modulus;
    }
}