package rest.mybatis.model.test;

import java.util.Date;

public class UserT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_LoginName
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userLoginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Name
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Password
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Validity
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Boolean userValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Office_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userOfficeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Email
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.Access_Priviledge
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Boolean accessPriviledge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.Access_Role
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer accessRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.Department_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.PRESALE_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Float presaleCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_State_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.SEX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.BIRTHDAY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.FAMILY_NAME1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String familyName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.FAMILY_TEL1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String familyTel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.FAMILY_NAME2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String familyName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.FAMILY_TEL2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String familyTel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.PAPER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer paperType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.PAPER_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String paperNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.COM_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String comNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_OLD_NAME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userOldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_FOLK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userFolk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_HOMETOWN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userHometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_PARTY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userParty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_MARRY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userMarry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_EDU_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userEduLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_DOOR_CITY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userDoorCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_FORM_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Date userFormTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_REGULAR_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Date userRegularTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_LEAVE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Date userLeaveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.MAIN_ROLE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer mainRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.LEAVE_DAYS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Double leaveDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.CORRECT_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer correctState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.CORRECT_DSC
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String correctDsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.TEL_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Float telCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.K3_UID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer k3Uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_MAC_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userMacAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.AGENT_COMP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer agentComp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.AGENT_POSITION
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer agentPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.BANKNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.HRNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String hrnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.ARTICLE_COUNT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer articleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.DY_COINS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer dyCoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USEREMAIL_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer useremailNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USERPRIVILEGE_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userprivilegeNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USERCOMNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer usercomnumNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USERHRNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userhrnumNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.COMNUM_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer comnumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.NOTICE_FIRSTFLAG
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer noticeFirstflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.LEAVE_DAYS_STANDARD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer leaveDaysStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.ROOM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_TEL_EX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userTelEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.PERSONAL_INFO_UPDATE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Date personalInfoUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.CORPRATION_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer corprationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_GRADE_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userGradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.USER_GRADE_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer userGradeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.OCCUPY_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Integer occupyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.APP_CODE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.OFFICE_COST_TOTAL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private Double officeCostTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserT.User_Description
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    private String userDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_ID
     *
     * @return the value of UserT.User_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_ID
     *
     * @param userId the value for UserT.User_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_LoginName
     *
     * @return the value of UserT.User_LoginName
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserLoginname() {
        return userLoginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_LoginName
     *
     * @param userLoginname the value for UserT.User_LoginName
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserLoginname(String userLoginname) {
        this.userLoginname = userLoginname == null ? null : userLoginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Name
     *
     * @return the value of UserT.User_Name
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Name
     *
     * @param userName the value for UserT.User_Name
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Password
     *
     * @return the value of UserT.User_Password
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Password
     *
     * @param userPassword the value for UserT.User_Password
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Validity
     *
     * @return the value of UserT.User_Validity
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Boolean getUserValidity() {
        return userValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Validity
     *
     * @param userValidity the value for UserT.User_Validity
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserValidity(Boolean userValidity) {
        this.userValidity = userValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Tel
     *
     * @return the value of UserT.User_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Tel
     *
     * @param userTel the value for UserT.User_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Office_Tel
     *
     * @return the value of UserT.User_Office_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserOfficeTel() {
        return userOfficeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Office_Tel
     *
     * @param userOfficeTel the value for UserT.User_Office_Tel
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserOfficeTel(String userOfficeTel) {
        this.userOfficeTel = userOfficeTel == null ? null : userOfficeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Email
     *
     * @return the value of UserT.User_Email
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Email
     *
     * @param userEmail the value for UserT.User_Email
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.Access_Priviledge
     *
     * @return the value of UserT.Access_Priviledge
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Boolean getAccessPriviledge() {
        return accessPriviledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.Access_Priviledge
     *
     * @param accessPriviledge the value for UserT.Access_Priviledge
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setAccessPriviledge(Boolean accessPriviledge) {
        this.accessPriviledge = accessPriviledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.Access_Role
     *
     * @return the value of UserT.Access_Role
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getAccessRole() {
        return accessRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.Access_Role
     *
     * @param accessRole the value for UserT.Access_Role
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setAccessRole(Integer accessRole) {
        this.accessRole = accessRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.Department_ID
     *
     * @return the value of UserT.Department_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.Department_ID
     *
     * @param departmentId the value for UserT.Department_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_TYPE
     *
     * @return the value of UserT.USER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_TYPE
     *
     * @param userType the value for UserT.USER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.PRESALE_COST
     *
     * @return the value of UserT.PRESALE_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Float getPresaleCost() {
        return presaleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.PRESALE_COST
     *
     * @param presaleCost the value for UserT.PRESALE_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPresaleCost(Float presaleCost) {
        this.presaleCost = presaleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_State_ID
     *
     * @return the value of UserT.User_State_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserStateId() {
        return userStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_State_ID
     *
     * @param userStateId the value for UserT.User_State_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserStateId(Integer userStateId) {
        this.userStateId = userStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.SEX
     *
     * @return the value of UserT.SEX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.SEX
     *
     * @param sex the value for UserT.SEX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.BIRTHDAY
     *
     * @return the value of UserT.BIRTHDAY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.BIRTHDAY
     *
     * @param birthday the value for UserT.BIRTHDAY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_ADD
     *
     * @return the value of UserT.USER_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserAdd() {
        return userAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_ADD
     *
     * @param userAdd the value for UserT.USER_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserAdd(String userAdd) {
        this.userAdd = userAdd == null ? null : userAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.FAMILY_NAME1
     *
     * @return the value of UserT.FAMILY_NAME1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getFamilyName1() {
        return familyName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.FAMILY_NAME1
     *
     * @param familyName1 the value for UserT.FAMILY_NAME1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setFamilyName1(String familyName1) {
        this.familyName1 = familyName1 == null ? null : familyName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.FAMILY_TEL1
     *
     * @return the value of UserT.FAMILY_TEL1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getFamilyTel1() {
        return familyTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.FAMILY_TEL1
     *
     * @param familyTel1 the value for UserT.FAMILY_TEL1
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setFamilyTel1(String familyTel1) {
        this.familyTel1 = familyTel1 == null ? null : familyTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.FAMILY_NAME2
     *
     * @return the value of UserT.FAMILY_NAME2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getFamilyName2() {
        return familyName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.FAMILY_NAME2
     *
     * @param familyName2 the value for UserT.FAMILY_NAME2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setFamilyName2(String familyName2) {
        this.familyName2 = familyName2 == null ? null : familyName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.FAMILY_TEL2
     *
     * @return the value of UserT.FAMILY_TEL2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getFamilyTel2() {
        return familyTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.FAMILY_TEL2
     *
     * @param familyTel2 the value for UserT.FAMILY_TEL2
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setFamilyTel2(String familyTel2) {
        this.familyTel2 = familyTel2 == null ? null : familyTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.PAPER_TYPE
     *
     * @return the value of UserT.PAPER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.PAPER_TYPE
     *
     * @param paperType the value for UserT.PAPER_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPaperType(Integer paperType) {
        this.paperType = paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.PAPER_NUM
     *
     * @return the value of UserT.PAPER_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getPaperNum() {
        return paperNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.PAPER_NUM
     *
     * @param paperNum the value for UserT.PAPER_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPaperNum(String paperNum) {
        this.paperNum = paperNum == null ? null : paperNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.COM_NUM
     *
     * @return the value of UserT.COM_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getComNum() {
        return comNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.COM_NUM
     *
     * @param comNum the value for UserT.COM_NUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setComNum(String comNum) {
        this.comNum = comNum == null ? null : comNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_OLD_NAME
     *
     * @return the value of UserT.USER_OLD_NAME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserOldName() {
        return userOldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_OLD_NAME
     *
     * @param userOldName the value for UserT.USER_OLD_NAME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserOldName(String userOldName) {
        this.userOldName = userOldName == null ? null : userOldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_FOLK
     *
     * @return the value of UserT.USER_FOLK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserFolk() {
        return userFolk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_FOLK
     *
     * @param userFolk the value for UserT.USER_FOLK
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserFolk(Integer userFolk) {
        this.userFolk = userFolk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_HOMETOWN
     *
     * @return the value of UserT.USER_HOMETOWN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserHometown() {
        return userHometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_HOMETOWN
     *
     * @param userHometown the value for UserT.USER_HOMETOWN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserHometown(String userHometown) {
        this.userHometown = userHometown == null ? null : userHometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_PARTY
     *
     * @return the value of UserT.USER_PARTY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserParty() {
        return userParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_PARTY
     *
     * @param userParty the value for UserT.USER_PARTY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserParty(Integer userParty) {
        this.userParty = userParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_MARRY
     *
     * @return the value of UserT.USER_MARRY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserMarry() {
        return userMarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_MARRY
     *
     * @param userMarry the value for UserT.USER_MARRY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserMarry(Integer userMarry) {
        this.userMarry = userMarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_EDU_LEVEL
     *
     * @return the value of UserT.USER_EDU_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserEduLevel() {
        return userEduLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_EDU_LEVEL
     *
     * @param userEduLevel the value for UserT.USER_EDU_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserEduLevel(Integer userEduLevel) {
        this.userEduLevel = userEduLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_DOOR_CITY
     *
     * @return the value of UserT.USER_DOOR_CITY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserDoorCity() {
        return userDoorCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_DOOR_CITY
     *
     * @param userDoorCity the value for UserT.USER_DOOR_CITY
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserDoorCity(Integer userDoorCity) {
        this.userDoorCity = userDoorCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_FORM_TIME
     *
     * @return the value of UserT.USER_FORM_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Date getUserFormTime() {
        return userFormTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_FORM_TIME
     *
     * @param userFormTime the value for UserT.USER_FORM_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserFormTime(Date userFormTime) {
        this.userFormTime = userFormTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_REGULAR_TIME
     *
     * @return the value of UserT.USER_REGULAR_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Date getUserRegularTime() {
        return userRegularTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_REGULAR_TIME
     *
     * @param userRegularTime the value for UserT.USER_REGULAR_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserRegularTime(Date userRegularTime) {
        this.userRegularTime = userRegularTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_LEAVE_TIME
     *
     * @return the value of UserT.USER_LEAVE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Date getUserLeaveTime() {
        return userLeaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_LEAVE_TIME
     *
     * @param userLeaveTime the value for UserT.USER_LEAVE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserLeaveTime(Date userLeaveTime) {
        this.userLeaveTime = userLeaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.MAIN_ROLE
     *
     * @return the value of UserT.MAIN_ROLE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getMainRole() {
        return mainRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.MAIN_ROLE
     *
     * @param mainRole the value for UserT.MAIN_ROLE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setMainRole(Integer mainRole) {
        this.mainRole = mainRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.LEAVE_DAYS
     *
     * @return the value of UserT.LEAVE_DAYS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Double getLeaveDays() {
        return leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.LEAVE_DAYS
     *
     * @param leaveDays the value for UserT.LEAVE_DAYS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setLeaveDays(Double leaveDays) {
        this.leaveDays = leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.CORRECT_STATE
     *
     * @return the value of UserT.CORRECT_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getCorrectState() {
        return correctState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.CORRECT_STATE
     *
     * @param correctState the value for UserT.CORRECT_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setCorrectState(Integer correctState) {
        this.correctState = correctState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.CORRECT_DSC
     *
     * @return the value of UserT.CORRECT_DSC
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getCorrectDsc() {
        return correctDsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.CORRECT_DSC
     *
     * @param correctDsc the value for UserT.CORRECT_DSC
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setCorrectDsc(String correctDsc) {
        this.correctDsc = correctDsc == null ? null : correctDsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.TEL_COST
     *
     * @return the value of UserT.TEL_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Float getTelCost() {
        return telCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.TEL_COST
     *
     * @param telCost the value for UserT.TEL_COST
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setTelCost(Float telCost) {
        this.telCost = telCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.K3_UID
     *
     * @return the value of UserT.K3_UID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getK3Uid() {
        return k3Uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.K3_UID
     *
     * @param k3Uid the value for UserT.K3_UID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setK3Uid(Integer k3Uid) {
        this.k3Uid = k3Uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_MAC_ADD
     *
     * @return the value of UserT.USER_MAC_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserMacAdd() {
        return userMacAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_MAC_ADD
     *
     * @param userMacAdd the value for UserT.USER_MAC_ADD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserMacAdd(String userMacAdd) {
        this.userMacAdd = userMacAdd == null ? null : userMacAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.AGENT_COMP
     *
     * @return the value of UserT.AGENT_COMP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getAgentComp() {
        return agentComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.AGENT_COMP
     *
     * @param agentComp the value for UserT.AGENT_COMP
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setAgentComp(Integer agentComp) {
        this.agentComp = agentComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.AGENT_POSITION
     *
     * @return the value of UserT.AGENT_POSITION
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getAgentPosition() {
        return agentPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.AGENT_POSITION
     *
     * @param agentPosition the value for UserT.AGENT_POSITION
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setAgentPosition(Integer agentPosition) {
        this.agentPosition = agentPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.BANKNUM
     *
     * @return the value of UserT.BANKNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.BANKNUM
     *
     * @param banknum the value for UserT.BANKNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.HRNUM
     *
     * @return the value of UserT.HRNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getHrnum() {
        return hrnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.HRNUM
     *
     * @param hrnum the value for UserT.HRNUM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setHrnum(String hrnum) {
        this.hrnum = hrnum == null ? null : hrnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.ARTICLE_COUNT
     *
     * @return the value of UserT.ARTICLE_COUNT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getArticleCount() {
        return articleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.ARTICLE_COUNT
     *
     * @param articleCount the value for UserT.ARTICLE_COUNT
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setArticleCount(Integer articleCount) {
        this.articleCount = articleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.DY_COINS
     *
     * @return the value of UserT.DY_COINS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getDyCoins() {
        return dyCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.DY_COINS
     *
     * @param dyCoins the value for UserT.DY_COINS
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setDyCoins(Integer dyCoins) {
        this.dyCoins = dyCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USEREMAIL_NEED
     *
     * @return the value of UserT.USEREMAIL_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUseremailNeed() {
        return useremailNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USEREMAIL_NEED
     *
     * @param useremailNeed the value for UserT.USEREMAIL_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUseremailNeed(Integer useremailNeed) {
        this.useremailNeed = useremailNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USERPRIVILEGE_NEED
     *
     * @return the value of UserT.USERPRIVILEGE_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserprivilegeNeed() {
        return userprivilegeNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USERPRIVILEGE_NEED
     *
     * @param userprivilegeNeed the value for UserT.USERPRIVILEGE_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserprivilegeNeed(Integer userprivilegeNeed) {
        this.userprivilegeNeed = userprivilegeNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USERCOMNUM_NEED
     *
     * @return the value of UserT.USERCOMNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUsercomnumNeed() {
        return usercomnumNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USERCOMNUM_NEED
     *
     * @param usercomnumNeed the value for UserT.USERCOMNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUsercomnumNeed(Integer usercomnumNeed) {
        this.usercomnumNeed = usercomnumNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USERHRNUM_NEED
     *
     * @return the value of UserT.USERHRNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserhrnumNeed() {
        return userhrnumNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USERHRNUM_NEED
     *
     * @param userhrnumNeed the value for UserT.USERHRNUM_NEED
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserhrnumNeed(Integer userhrnumNeed) {
        this.userhrnumNeed = userhrnumNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.COMNUM_TYPE
     *
     * @return the value of UserT.COMNUM_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getComnumType() {
        return comnumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.COMNUM_TYPE
     *
     * @param comnumType the value for UserT.COMNUM_TYPE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setComnumType(Integer comnumType) {
        this.comnumType = comnumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.NOTICE_FIRSTFLAG
     *
     * @return the value of UserT.NOTICE_FIRSTFLAG
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getNoticeFirstflag() {
        return noticeFirstflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.NOTICE_FIRSTFLAG
     *
     * @param noticeFirstflag the value for UserT.NOTICE_FIRSTFLAG
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setNoticeFirstflag(Integer noticeFirstflag) {
        this.noticeFirstflag = noticeFirstflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.LEAVE_DAYS_STANDARD
     *
     * @return the value of UserT.LEAVE_DAYS_STANDARD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getLeaveDaysStandard() {
        return leaveDaysStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.LEAVE_DAYS_STANDARD
     *
     * @param leaveDaysStandard the value for UserT.LEAVE_DAYS_STANDARD
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setLeaveDaysStandard(Integer leaveDaysStandard) {
        this.leaveDaysStandard = leaveDaysStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.ROOM
     *
     * @return the value of UserT.ROOM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.ROOM
     *
     * @param room the value for UserT.ROOM
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setRoom(Integer room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_TEL_EX
     *
     * @return the value of UserT.USER_TEL_EX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserTelEx() {
        return userTelEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_TEL_EX
     *
     * @param userTelEx the value for UserT.USER_TEL_EX
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserTelEx(String userTelEx) {
        this.userTelEx = userTelEx == null ? null : userTelEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.PERSONAL_INFO_UPDATE_TIME
     *
     * @return the value of UserT.PERSONAL_INFO_UPDATE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Date getPersonalInfoUpdateTime() {
        return personalInfoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.PERSONAL_INFO_UPDATE_TIME
     *
     * @param personalInfoUpdateTime the value for UserT.PERSONAL_INFO_UPDATE_TIME
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setPersonalInfoUpdateTime(Date personalInfoUpdateTime) {
        this.personalInfoUpdateTime = personalInfoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.CORPRATION_ID
     *
     * @return the value of UserT.CORPRATION_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getCorprationId() {
        return corprationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.CORPRATION_ID
     *
     * @param corprationId the value for UserT.CORPRATION_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setCorprationId(Integer corprationId) {
        this.corprationId = corprationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_GRADE_ID
     *
     * @return the value of UserT.USER_GRADE_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserGradeId() {
        return userGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_GRADE_ID
     *
     * @param userGradeId the value for UserT.USER_GRADE_ID
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserGradeId(Integer userGradeId) {
        this.userGradeId = userGradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.USER_GRADE_LEVEL
     *
     * @return the value of UserT.USER_GRADE_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getUserGradeLevel() {
        return userGradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.USER_GRADE_LEVEL
     *
     * @param userGradeLevel the value for UserT.USER_GRADE_LEVEL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserGradeLevel(Integer userGradeLevel) {
        this.userGradeLevel = userGradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.OCCUPY_STATE
     *
     * @return the value of UserT.OCCUPY_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Integer getOccupyState() {
        return occupyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.OCCUPY_STATE
     *
     * @param occupyState the value for UserT.OCCUPY_STATE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setOccupyState(Integer occupyState) {
        this.occupyState = occupyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.APP_CODE
     *
     * @return the value of UserT.APP_CODE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.APP_CODE
     *
     * @param appCode the value for UserT.APP_CODE
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.OFFICE_COST_TOTAL
     *
     * @return the value of UserT.OFFICE_COST_TOTAL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public Double getOfficeCostTotal() {
        return officeCostTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.OFFICE_COST_TOTAL
     *
     * @param officeCostTotal the value for UserT.OFFICE_COST_TOTAL
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setOfficeCostTotal(Double officeCostTotal) {
        this.officeCostTotal = officeCostTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserT.User_Description
     *
     * @return the value of UserT.User_Description
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserT.User_Description
     *
     * @param userDescription the value for UserT.User_Description
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription == null ? null : userDescription.trim();
    }
}