package rest.mybatis.dao.test;

import rest.mybatis.model.test.Pline;
import rest.mybatis.model.test.PlineWithBLOBs;

public interface PlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int insert(PlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int insertSelective(PlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    PlineWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKeySelective(PlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLIN
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKey(Pline record);
}