package rest.mybatis.dao.test;

import rest.mybatis.model.test.ProBu;

public interface ProBuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int insert(ProBu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int insertSelective(ProBu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    ProBu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int updateByPrimaryKeySelective(ProBu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO_BU
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int updateByPrimaryKey(ProBu record);
}