package rest.mybatis.dao.test;

import rest.mybatis.model.test.Pro;
import rest.mybatis.model.test.ProWithBLOBs;

public interface ProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int insert(ProWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int insertSelective(ProWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    ProWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKeySelective(ProWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ProWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRO
     *
     * @mbggenerated Mon Nov 28 14:58:32 CST 2016
     */
    int updateByPrimaryKey(Pro record);
}