package rest.mybatis.dao.test;

import rest.mybatis.model.test.UserT;

public interface UserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int insert(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int insertSelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    UserT selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int updateByPrimaryKeySelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Dec 01 10:26:39 CST 2016
     */
    int updateByPrimaryKey(UserT record);
}